name: publish
on:
  push:
    branches:
      - main

jobs:
  publish-prod-docker-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/rehark/lead_dev:prod
          docker push ghcr.io/rehark/lead_dev:prod
    